### ISSUE TITLE
Make the Background of the App Icon Transparent 

### ISSUE THREAD

**Issue by kiliandreyer** [Alex313031/Thorium-Android#20]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like, including relevant patches or source**

**Additional Notes**

**Comment by squidds** [comment]
Judging from looking at the history of the developer of this app, this was likely a small oversight and will be resolved in a future update. I would expect ver. 118 update to be released sometime in the near future. In the meantime if you are not using the stock android launcher you can just change the icon. That's what I did. Delta Icon Pack on F-Droid is a good free icon pack. I am using the chrome icon because Chrome is already completely disabled on my devices

**Comment by ghost** [comment]
Would be nice actually
